name: Deploy Server to Render

on:
  push:
    branches:
      - production

jobs:
  ci-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # - name: Run tests (Uncomment if you have tests configured)
      #   run: npm test

      - name: Trigger Render Deploy Hook
        run: |
          curl -f -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
